[package]
name = "mahnung"
version = "0.1.0"
authors = ["Lalit Umbarkar <lalit.umbarkar9@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cron_tab = "0.1.0"
chrono = "0.4.13"
notify-rust = "4.0.0"
